version: '3.9'

services:
  bortube_video_microservice:
    build:
      context: ../../Backend/BorTube-Video-Microservice
      dockerfile: Dockerfile
    container_name: bortube_video_microservice_container

  bortube_video_uploading_microservice:
    build:
      context: ../../Backend/BorTube-Video-Upload-Microservice
      dockerfile: Dockerfile
    container_name: bortube_video_uploading_microservice_container

  bortube_user_microservice:
    build:
      context: ../../Backend/BorTube-User-Microservice
      dockerfile: Dockerfile
    container_name: bortube_user_microservice_container

  bortube_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bortube_gateway_container
    ports:
      - "8000:8000"

  bortube_frontend:
    build:
      context: ../../Frontend/BorTube-frontend
      dockerfile: Dockerfile
    container_name: bortube_frontend-container
    ports:
      - "8080:80"